### ISSUE TITLE
[Epic: js-waku] User Pays Own RLN Membership

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/pm#109]
**Epic label**: `E:js-waku User Pays Own RLN Membership`

# Summary

Enable developers to build application where the users pays for their own credentials.

# Acceptance Criteria

- A developer can build a web app for which a user generate credentials and push them to the RLN smart contract.
- The API needs to be simple enough so it is usable in a hackathon and can be documented.
- Import/export to keystore JSON file is supported

# Tasks

- [ ] https://github.com/waku-org/js-rln/issues/76
- [x] https://github.com/waku-org/js-rln/issues/25

# Notes

For the sake of developer experience, the API should be simple and easy to use (e.g. in less than 20 lines). This means that the library may need to be opinionated in the way contract events are handled, what web3 library is used (etherjs), etc.

Consideration needs to be made on how to handle that in the js-waku package ecosystem. For example. should this be part of the `@waku/sdk` (I would suggest yes).

Notes that https://github.com/waku-org/research/issues/45 is not in the scope of the issue. The intent is to get RLN in the hands of developer, the second priority will be to fix the UX.

**Comment by weboko** [comment]
Execution plan

**Step 1**: improve bootstrapping and connection to ethereum

Metamask:
- abstraction to get provider with triggering dialog from Metamask
- ability to pass it from outside

RLN Instance:
- dedicated step for starting: bootstraps RLN Contract
- expose RLN contract from instance

**Step 2**: improve cred management, verification

Keystore
- easy way to import or hardcode credentials
- easier way to register credential (use case: simple chat app, e.g light-js)

Verification:
- embed verification into DecodedMessage so that all messages received can be verified;

**Step 3**: include into `@waku/sdk` and improve RLN instance interface

RLN Instance:
- make it resembling Waku node: rln contract exposed;
- separation of member management and proof verification;

Files: 
- do basic reorganization: e.g rln.ts is too chunky

**Comment by weboko** [comment]
Leftovers: merge examples, better integration with `@waku/sdk`, improve credentials handling, documentation

**Comment by fryorcraken** [comment]
This is descoped in favour of deliverable "Provision RLN for light push clients PoC" cc @chair28980

**Comment by weboko** [comment]
Closing as the only leftover is https://github.com/waku-org/js-rln/issues/76 and can be done separately when in priority again.
