### ISSUE TITLE
[Milestone] RLN v2

### ISSUE THREAD

**Issue by chair28980** [waku-org/pm#163]
_Research Milestone_

Milestone: https://github.com/waku-org/pm/milestone/25
Project: https://github.com/orgs/waku-org/projects/21/views/1

## Epics
- [ ] research: 
- [x] nwaku: https://github.com/waku-org/nwaku/issues/2345
- [ ] docs:

**Comment by alrevuelta** [comment]
Closing, most of the work done in https://github.com/waku-org/nwaku/issues/2345 and https://github.com/waku-org/pm/issues/168 now tracks the shipping of this feature into TheWakuNetwork. Using a new milestone since this feature will be shipped together with another one, to avoid introducing multiple breaking changes.
